version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - PROFILE_IMAGE_PATH=${PROFILE_IMAGE_PATH}
    volumes:
      - ./telegram_bot.py:/usr/src/app/telegram_bot.py
      - ./Profiles/:/usr/src/app/Profiles/
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: